import { AREAS } from './types.js';

export const ACTIONS = {
  [AREAS.PHYSICAL]: [
    {
      day: 1,
      duration: '≈ 10 min',
      text: "Camina deu minuts a un ritme que et faci respirar més fort. No més, no menys.",
      metadata: {
        mode: 'body',
        setting: 'outside',
        social: 'solo',
        intensity: 'medium',
        autonomySignal: 'vas regular el ritme sense convertir-ho en entrenament',
        capacitySignal: 'cos en marxa i ritme sostingut',
        motivationSignal: 'sortir i notar aire pot donar una mica de tracció',
        nextSmallStep: 'camina tres minuts a prop de casa i atura’t abans de cansar-te',
      },
    },
    {
      day: 2,
      duration: '≈ 3 min',
      text: "Aixeca't de la cadira i torna-hi cinc vegades, sense ajudar-te amb les mans.",
      metadata: {
        mode: 'body',
        setting: 'inside',
        social: 'solo',
        intensity: 'medium',
        autonomySignal: 'vas provar una acció molt concreta amb el que tenies a mà',
        capacitySignal: 'força bàsica i control del gest',
        motivationSignal: 'veure un gest completat pot donar sensació d’entrada',
        nextSmallStep: 'fes dues aixecades de cadira i deixa-ho aquí',
      },
    },
    {
      day: 3,
      duration: '≈ 4 min',
      text: "Apreta una tovallola doblegada fermament, sense forçar, durant deu segons per cada mà.",
      metadata: {
        mode: 'body',
        setting: 'inside',
        social: 'solo',
        intensity: 'low',
        autonomySignal: 'vas adaptar una prova amb un objecte quotidià',
        capacitySignal: 'força suau de mans i atenció al límit',
        motivationSignal: 'un gest petit pot fer present el cos sense pressa',
        nextSmallStep: 'apreta una tovallola cinc segons amb cada mà, sense forçar',
      },
    },
    {
      day: 4,
      duration: '≈ 3 min',
      text: "Mantén-te en equilibri sobre una cama durant trenta segons per costat, ulls oberts i prop d'una paret.",
      metadata: {
        mode: 'body',
        setting: 'inside',
        social: 'solo',
        intensity: 'medium',
        autonomySignal: 'vas posar una protecció clara abans de provar',
        capacitySignal: 'equilibri i confiança corporal',
        motivationSignal: 'aguantar uns segons pot donar una referència simple',
        nextSmallStep: 'mantén l’equilibri deu segons per costat amb una paret a prop',
      },
    },
    {
      day: 5,
      duration: '≈ 5 min',
      text: "Mou tres parts del cos cinc cops cadascuna: coll amb girs lents, espatlles enrere i cintura amb girs petits. Sense forçar.",
      metadata: {
        mode: 'body',
        setting: 'inside',
        social: 'solo',
        intensity: 'low',
        autonomySignal: 'vas triar moviments petits i controlats',
        capacitySignal: 'mobilitat suau i escolta corporal',
        motivationSignal: 'activar el cos sense exigir pot deixar una porta oberta',
        nextSmallStep: 'mou només espatlles i coll tres cops, lentament',
      },
    },
    {
      day: 6,
      duration: '≈ 10 min',
      text: "Repeteix la caminada del primer dia i observa com et sents. No cal anar més lluny.",
      metadata: {
        mode: 'body',
        setting: 'outside',
        social: 'solo',
        intensity: 'medium',
        autonomySignal: 'vas comparar una prova sense haver d’anar més lluny',
        capacitySignal: 'ritme, observació i continuïtat',
        motivationSignal: 'repetir pot donar una mesura senzilla del que encaixa',
        nextSmallStep: 'repeteix només el primer tram de la caminada i torna',
      },
    },
  ],
  [AREAS.COGNITIVE]: [
    {
      day: 1,
      duration: '≈ 5 min',
      text: "Aprèn una paraula nova en una llengua que no parlis. Repeteix-la cinc vegades i demà intenta recordar-la sense mirar.",
      metadata: {
        mode: 'memory',
        setting: 'inside',
        social: 'solo',
        intensity: 'low',
        autonomySignal: 'vas obrir una cosa nova sense necessitat d’encertar-la del tot',
        capacitySignal: 'aprenentatge breu i record diferit',
        motivationSignal: 'una paraula nova pot activar curiositat',
        nextSmallStep: 'tria una paraula nova i repeteix-la només tres vegades',
      },
    },
    {
      day: 2,
      duration: '≈ 5 min',
      text: "Recorda què vas dinar fa tres dies. Anota-ho i, si pots, verifica-ho després amb la nevera, el calendari o algú de casa.",
      metadata: {
        mode: 'memory',
        setting: 'inside',
        social: 'solo',
        intensity: 'medium',
        autonomySignal: 'vas buscar una pista concreta abans de verificar',
        capacitySignal: 'memòria quotidiana i contrast amb pistes',
        motivationSignal: 'lligar record i vida diària pot fer-ho més útil',
        nextSmallStep: 'anota només un detall d’un àpat recent i verifica’l després',
      },
    },
    {
      day: 3,
      duration: '≈ 6 min',
      text: "Memoritza set objectes que veus a l'habitació. Recita'ls d'aquí cinc minuts.",
      metadata: {
        mode: 'memory',
        setting: 'inside',
        social: 'solo',
        intensity: 'medium',
        autonomySignal: 'vas ordenar l’atenció en un espai conegut',
        capacitySignal: 'atenció visual i record a curt termini',
        motivationSignal: 'jugar amb objectes propers pot fer la prova menys abstracta',
        nextSmallStep: 'memoriza tres objectes de l’habitació i digues-los al cap d’un minut',
      },
    },
    {
      day: 4,
      duration: '≈ 4 min',
      text: "Calcula mentalment 24 + 15. Sense paper ni calculadora. Després, si vols, verifica-ho.",
      metadata: {
        mode: 'memory',
        setting: 'inside',
        social: 'solo',
        intensity: 'medium',
        autonomySignal: 'vas sostenir una operació curta abans de mirar el resultat',
        capacitySignal: 'càlcul mental i atenció sostinguda',
        motivationSignal: 'una resposta clara pot donar tancament ràpid',
        nextSmallStep: 'fes una suma més petita, com 12 + 7, i verifica-la',
      },
    },
    {
      day: 5,
      duration: '≈ 5 min',
      text: "Explica en veu alta un concepte que coneguis, com la teva feina, una afició o una recepta, com si parlessis a algú de vuit anys.",
      metadata: {
        mode: 'memory',
        setting: 'inside',
        social: 'solo',
        intensity: 'medium',
        autonomySignal: 'vas posar ordre a una cosa que ja forma part de tu',
        capacitySignal: 'llenguatge, síntesi i memòria personal',
        motivationSignal: 'explicar el que saps pot reconnectar amb habilitat pròpia',
        nextSmallStep: 'explica una recepta o afició en tres frases',
      },
    },
    {
      day: 6,
      duration: '≈ 6 min',
      text: "Anota tres coses que vas fer ahir, en ordre cronològic. Demà, comprova si te'n recordes sense llegir l'anotació.",
      metadata: {
        mode: 'memory',
        setting: 'inside',
        social: 'solo',
        intensity: 'low',
        autonomySignal: 'vas fer servir l’escriptura com a suport propi',
        capacitySignal: 'seqüència, record i revisió',
        motivationSignal: 'veure el fil d’un dia pot donar continuïtat',
        nextSmallStep: 'anota dues coses d’ahir en ordre i deixa el paper visible',
      },
    },
  ],
  [AREAS.STRESS]: [
    {
      day: 1,
      duration: '≈ 3 min',
      text: "Asseu-te en silenci tres minuts, sense fer res. Compta les respiracions.",
      metadata: {
        mode: 'calm',
        setting: 'inside',
        social: 'solo',
        intensity: 'low',
        autonomySignal: 'vas obrir una pausa sense haver de resoldre res',
        capacitySignal: 'aturada breu i atenció a la respiració',
        motivationSignal: 'tres minuts poden fer que començar sigui menys pesat',
        nextSmallStep: 'seu un minut i compta només cinc respiracions',
      },
    },
    {
      day: 2,
      duration: '≈ 10 min',
      text: "Apaga les notificacions del mòbil durant deu minuts. Fes alguna cosa amb les mans: plegar roba, regar plantes o pelar fruita.",
      metadata: {
        mode: 'calm',
        setting: 'inside',
        social: 'solo',
        intensity: 'medium',
        autonomySignal: 'vas decidir quin estímul deixaves fora una estona',
        capacitySignal: 'control d’atenció i tasca manual',
        motivationSignal: 'notar menys interrupcions pot donar espai',
        nextSmallStep: 'posa el mòbil en silenci tres minuts i fes una tasca amb les mans',
      },
    },
    {
      day: 3,
      duration: '≈ 3 min',
      text: "Surt a fora i mira l'horitzó un minut, sense pantalles. Després respira dues vegades lent.",
      metadata: {
        mode: 'calm',
        setting: 'outside',
        social: 'solo',
        intensity: 'low',
        autonomySignal: 'vas canviar d’escena per uns minuts',
        capacitySignal: 'pausa visual i respiració lenta',
        motivationSignal: 'mirar lluny pot donar una mica d’obertura',
        nextSmallStep: 'obre una finestra o surt al replà i mira lluny trenta segons',
      },
    },
    {
      day: 4,
      duration: '≈ 4 min',
      text: "Localitza una tensió física, com coll, espatlles o mandíbula. Posa-hi la mà a sobre i respira lent durant trenta segons.",
      metadata: {
        mode: 'calm',
        setting: 'inside',
        social: 'solo',
        intensity: 'low',
        autonomySignal: 'vas escoltar una senyal del cos sense discutir-la',
        capacitySignal: 'reconeixement de tensió i regulació suau',
        motivationSignal: 'posar-hi la mà pot fer la pausa més concreta',
        nextSmallStep: 'posa la mà a coll o espatlles i respira lent tres vegades',
      },
    },
    {
      day: 5,
      duration: '≈ 10 min',
      text: "No obris el mòbil els primers deu minuts del matí. Abans fes una cosa lenta: cafè, finestra o una petita tasca de casa.",
      metadata: {
        mode: 'calm',
        setting: 'inside',
        social: 'solo',
        intensity: 'medium',
        autonomySignal: 'vas protegir el primer tram del dia',
        capacitySignal: 'inici lent i elecció d’un ritme propi',
        motivationSignal: 'començar sense pantalla pot donar més presència',
        nextSmallStep: 'abans del mòbil, fes només un minut de cafè, finestra o aigua',
      },
    },
    {
      day: 6,
      duration: '≈ 5 min',
      text: "Mentre fas una activitat habitual, com rentar plats o caminar, compta cinc respiracions completes sense interrompre l'activitat.",
      metadata: {
        mode: 'calm',
        setting: 'either',
        social: 'solo',
        intensity: 'low',
        autonomySignal: 'vas inserir una pausa dins una acció normal',
        capacitySignal: 'atenció mentre continues fent vida',
        motivationSignal: 'no haver d’aturar-ho tot pot fer-ho més viable',
        nextSmallStep: 'compta tres respiracions mentre fas una tasca habitual',
      },
    },
  ],
  [AREAS.RELATIONAL]: [
    {
      day: 1,
      duration: '≈ 5 min',
      text: "Envia un missatge curt a algú amb qui no parlis fa més d'un mes. Si et ve de gust, proposa una trucada breu.",
      metadata: {
        mode: 'social',
        setting: 'either',
        social: 'message',
        intensity: 'medium',
        autonomySignal: 'vas triar una persona concreta i un primer contacte petit',
        capacitySignal: 'inici de contacte i decisió social',
        motivationSignal: 'recuperar un fil pot donar una mica de ganes',
        nextSmallStep: 'envia només una frase a una persona concreta, sense proposta afegida',
      },
    },
    {
      day: 2,
      duration: '≈ 3 min',
      text: "Saluda algú que veus sovint però no coneixes. Si no es dona el moment, envia un missatge curt a algú proper.",
      metadata: {
        mode: 'social',
        setting: 'either',
        social: 'with_person',
        intensity: 'low',
        autonomySignal: 'vas deixar oberta una forma alternativa si el moment no sortia',
        capacitySignal: 'microcontacte i presència',
        motivationSignal: 'un gest breu pot fer el dia menys tancat',
        nextSmallStep: 'saluda una persona o envia un missatge de dues paraules a algú proper',
      },
    },
    {
      day: 3,
      duration: '≈ 4 min',
      text: "Escriu un missatge curt a algú només per dir-li que l'has pensat. Sense demanar res.",
      metadata: {
        mode: 'social',
        setting: 'either',
        social: 'message',
        intensity: 'low',
        autonomySignal: 'vas contactar sense haver de demanar ni justificar res',
        capacitySignal: 'gest afectiu simple i inici de vincle',
        motivationSignal: 'fer saber que has pensat algú pot encendre calidesa',
        nextSmallStep: 'escriu “he pensat en tu” a algú i no hi afegeixis cap demanda',
      },
    },
    {
      day: 4,
      duration: '≈ 3 min',
      text: "Tingues una conversa de tres minuts sense mirar el mòbil. Si no hi ha ningú disponible ara, envia un àudio o un missatge curt amb una pregunta concreta.",
      metadata: {
        mode: 'social',
        setting: 'either',
        social: 'with_person',
        intensity: 'medium',
        autonomySignal: 'vas protegir una conversa d’una interrupció habitual',
        capacitySignal: 'atenció compartida i pregunta concreta',
        motivationSignal: 'estar present uns minuts pot donar qualitat al contacte',
        nextSmallStep: 'fes una pregunta concreta i deixa el mòbil apartat un minut',
      },
    },
    {
      day: 5,
      duration: '≈ 6 min',
      text: "Pregunta a algú una cosa que no li havies preguntat mai, com què recorda d'una etapa que no t'ha explicat. Si no pot contestar ara, escriu la pregunta i envia-la per missatge.",
      metadata: {
        mode: 'social',
        setting: 'either',
        social: 'message',
        intensity: 'medium',
        autonomySignal: 'vas obrir una conversa amb curiositat concreta',
        capacitySignal: 'escolta, pregunta i interès per l’altre',
        motivationSignal: 'descobrir una història pot donar interès real',
        nextSmallStep: 'envia una sola pregunta amable sobre un record concret',
      },
    },
    {
      day: 6,
      duration: '≈ 4 min',
      text: "Reconeix una virtut d'una persona amb qui sovint discrepes. En directe o en un missatge molt breu.",
      metadata: {
        mode: 'social',
        setting: 'either',
        social: 'message',
        intensity: 'medium',
        autonomySignal: 'vas separar una qualitat de la discrepància',
        capacitySignal: 'mirada relacional i reconeixement',
        motivationSignal: 'dir una virtut pot obrir una relació més respirable',
        nextSmallStep: 'escriu una qualitat concreta d’algú sense entrar en cap discussió',
      },
    },
  ],
  [AREAS.IDENTITY]: [
    {
      day: 1,
      duration: '≈ 5 min',
      text: "Canvia una microdecisió habitual: ruta, beguda, música o seient. Observa com et queda durant cinc minuts.",
      metadata: {
        mode: 'purpose',
        setting: 'either',
        social: 'solo',
        intensity: 'low',
        autonomySignal: 'vas tocar una rutina sense haver de canviar gaire cosa',
        capacitySignal: 'decisió petita i observació personal',
        motivationSignal: 'una variació mínima pot donar sensació de joc',
        nextSmallStep: 'canvia només una decisió petita, com música o seient',
      },
    },
    {
      day: 2,
      duration: '≈ 5 min',
      text: "Agafa un paper i completa dues línies: \"Sovint faig...\" i \"Avui faré una excepció petita: ...\". Fes aquesta excepció abans de tancar el dia.",
      metadata: {
        mode: 'purpose',
        setting: 'inside',
        social: 'solo',
        intensity: 'medium',
        autonomySignal: 'vas posar nom a una rutina i vas triar una excepció',
        capacitySignal: 'decisió pròpia i pas concret',
        motivationSignal: 'fer una excepció petita pot donar aire a la setmana',
        nextSmallStep: 'escriu només “avui faré una excepció petita” i completa una línia',
      },
    },
    {
      day: 3,
      duration: '≈ 4 min',
      text: "Escriu en un paper una opinió ferma en una frase. A sota, escriu dues raons que defensarien la posició contrària i llegeix-les en veu alta.",
      metadata: {
        mode: 'purpose',
        setting: 'inside',
        social: 'solo',
        intensity: 'medium',
        autonomySignal: 'vas provar flexibilitat sense abandonar el teu criteri',
        capacitySignal: 'perspectiva, llenguatge i marge mental',
        motivationSignal: 'mirar una idea per dos costats pot despertar curiositat',
        nextSmallStep: 'escriu una opinió i només una raó possible de l’altra banda',
      },
    },
    {
      day: 4,
      duration: '≈ 6 min',
      text: "Escriu el nom d'una activitat que t'agradava fer als trenta. A sota, apunta el primer pas petit per reprendre-la aquesta setmana i deixa'l en un lloc visible.",
      metadata: {
        mode: 'purpose',
        setting: 'inside',
        social: 'solo',
        intensity: 'medium',
        autonomySignal: 'vas recuperar una activitat pròpia en una forma petita',
        capacitySignal: 'memòria personal i primer pas visible',
        motivationSignal: 'recordar una activitat estimada pot tornar a encendre interès',
        nextSmallStep: 'escriu una activitat que t’agradava i deixa només el nom visible',
      },
    },
    {
      day: 5,
      duration: '≈ 5 min',
      text: "Tria un objecte, llibre o idea que ja no fas servir i pensa a qui li podria servir. Si ho tens clar, prepara'l.",
      metadata: {
        mode: 'purpose',
        setting: 'inside',
        social: 'solo',
        intensity: 'low',
        autonomySignal: 'vas decidir què conservar, moure o oferir',
        capacitySignal: 'tria, ordre i sentit pràctic',
        motivationSignal: 'donar sortida a una cosa pot fer espai',
        nextSmallStep: 'tria un sol objecte i decideix si el deixes on és o el mous',
      },
    },
    {
      day: 6,
      duration: '≈ 5 min',
      text: "Agafa un paper i completa tres frases: \"Aquesta setmana he provat...\", \"M'ha costat...\" i \"Demà repetiré o deixaré descansar...\".",
      metadata: {
        mode: 'purpose',
        setting: 'inside',
        social: 'solo',
        intensity: 'low',
        autonomySignal: 'vas tancar el cicle amb una decisió pròpia sobre què repetir',
        capacitySignal: 'revisió, criteri i tria del pas següent',
        motivationSignal: 'mirar què has provat pot donar sentit al següent gest',
        nextSmallStep: 'completa només “demà repetiré o deixaré descansar...”',
      },
    },
  ],
};

export function durationToMinutes(duration) {
  const match = duration?.match(/\d+/);
  if (!match) return null;
  return Number(match[0]);
}

export function isActionDurationInRange(action, min = 3, max = 10) {
  const minutes = durationToMinutes(action?.duration);
  return Number.isFinite(minutes) && minutes >= min && minutes <= max;
}

export function getAllActions() {
  return Object.values(ACTIONS).flat();
}

function buildActionSteps(action) {
  return [
    'Prepara-ho: deixa a mà el que necessitis.',
    action.text,
    'Tanca-ho: marca el resultat.',
  ];
}

export function getAction(area, dayInCycle) {
  if (dayInCycle < 1 || dayInCycle > 6) return null;
  const action = ACTIONS[area]?.[dayInCycle - 1] || null;
  if (!action) return null;
  return {
    ...action,
    steps: buildActionSteps(action),
  };
}
